// Sample seed data for Gojipedia
// This provides realistic data for development and testing

import type {
  Monster,
  Work,
  Appearance,
  Battle,
  BattleParticipant,
  Relationship,
  Product,
  ProductCollection,
  ProductCollectionItem,
  Post,
} from '@/types';

// ============================================================================
// MONSTERS
// ============================================================================

export const sampleMonsters: Monster[] = [
  {
    id: 'monster-godzilla',
    name: 'Godzilla',
    slug: 'godzilla',
    aliases: ['Gojira', 'King of the Monsters', 'The Big G'],
    eraTags: ['Showa', 'Heisei', 'Millennium', 'Reiwa', 'MonsterVerse'],
    alignment: 'evolves',
    speciesType: 'kaiju',
    firstAppearanceDate: new Date('1954-11-03'),
    firstAppearanceWorkId: 'work-godzilla-1954',
    heightMeters: 119.8,
    weightTons: 99634,
    originSummary: 'An ancient alpha predator awakened and mutated by nuclear radiation. Originally a prehistoric creature that fed on natural radiation, Godzilla emerged from the depths of the Pacific Ocean after nuclear tests disturbed his slumber. He embodies the consequences of nuclear hubris while also serving as a force of natural balance.',
    lastKnownWhereabouts: 'Hollow Earth monitoring stations detected movement near the Antarctic entrance.',
    descriptionLong: 'Godzilla stands as the most recognized kaiju in cinematic history. His role has shifted dramatically across eras, from a terrifying metaphor for nuclear devastation to a defender of Earth against cosmic and terrestrial threats. The creature possesses remarkable regenerative abilities, powered by an internal nuclear reactor that also fuels his signature atomic breath. Intelligence assessments suggest problem-solving capabilities exceeding most terrestrial species.',
    abilities: ['Atomic Breath', 'Nuclear Pulse', 'Amphibious', 'Regeneration', 'Radiation Absorption', 'Extreme Durability'],
    attacks: ['Atomic Heat Ray', 'Nuclear Pulse Shockwave', 'Tail Swipe', 'Bite'],
    weaknesses: ['Oxygen Destroyer', 'Cadmium Missiles', 'Anti-Nuclear Energy Bacteria', 'Concentrated Cold'],
    fanPowerIndex: 95,
    durabilityScore: 98,
    attackPowerScore: 95,
    mobilityScore: 60,
    intelligenceScore: 85,
    specialAbilitiesScore: 92,
    eraScalingFactor: 1.2,
    primaryImageUrl: 'https://placehold.co/800x600/1a1a25/00d4aa?text=Godzilla',
    galleryImages: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'monster-mothra',
    name: 'Mothra',
    slug: 'mothra',
    aliases: ['Queen of the Monsters', 'The Guardian', 'Mosura'],
    eraTags: ['Showa', 'Heisei', 'Millennium', 'MonsterVerse'],
    alignment: 'protagonist',
    speciesType: 'kaiju',
    firstAppearanceDate: new Date('1961-07-30'),
    firstAppearanceWorkId: 'work-mothra-1961',
    heightMeters: 15.8,
    weightTons: 20000,
    originSummary: 'An ancient divine moth deity worshipped by the people of Infant Island. Mothra represents the benevolent side of nature, emerging to protect humanity and maintain planetary balance. She possesses a unique lifecycle, dying and being reborn through eggs guarded by the Shobijin priestesses.',
    lastKnownWhereabouts: 'Remains dormant in cocoon form at Temple of the Moth on Infant Island, awaiting the next crisis.',
    descriptionLong: 'Mothra occupies a unique position in the kaiju pantheon as an explicitly heroic figure. Unlike most titans who act on instinct or territorial imperative, Mothra demonstrates clear intentionality in defending human populations. Her symbiotic relationship with the Shobijin twins provides a communication channel between species. Research suggests her bioluminescent scales contain compounds with remarkable restorative properties.',
    abilities: ['Flight', 'Reflective Scales', 'Silk Spray', 'God Rays', 'Symbiotic Bond with Shobijin', 'Reincarnation'],
    attacks: ['Antenna Lightning', 'Wing Buffet', 'Poisonous Scales', 'Kamikaze Assault'],
    weaknesses: ['Fire', 'Limited Combat Durability', 'Dependence on Egg Cycle'],
    fanPowerIndex: 78,
    durabilityScore: 55,
    attackPowerScore: 65,
    mobilityScore: 95,
    intelligenceScore: 90,
    specialAbilitiesScore: 88,
    eraScalingFactor: 1.0,
    primaryImageUrl: 'https://placehold.co/800x600/1a1a25/00d4aa?text=Mothra',
    galleryImages: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'monster-king-ghidorah',
    name: 'King Ghidorah',
    slug: 'king-ghidorah',
    aliases: ['Ghidorah', 'Monster Zero', 'The One Who Is Many', 'The Golden Demise'],
    eraTags: ['Showa', 'Heisei', 'Millennium', 'MonsterVerse'],
    alignment: 'antagonist',
    speciesType: 'alien',
    firstAppearanceDate: new Date('1964-12-20'),
    firstAppearanceWorkId: 'work-ghidorah-three-headed-monster',
    heightMeters: 158.8,
    weightTons: 141056,
    originSummary: 'An extraterrestrial three-headed dragon of unknown origin. King Ghidorah travels between planets, leaving extinction-level destruction in his wake. Evidence suggests he may predate the formation of Earth itself, with civilizations across the galaxy sharing myths of a golden dragon that devours worlds.',
    lastKnownWhereabouts: 'The severed head recovered by Monarch from the Gulf of Mexico remains in containment. Status of the original entity unknown.',
    descriptionLong: 'King Ghidorah represents an existential threat on a scale beyond any terrestrial kaiju. Each of his three heads demonstrates distinct personality traits while maintaining coordination in combat. The creature generates hurricane-force winds through wing movement alone, and his gravity beams can level entire city blocks. Perhaps most concerning, Ghidorah shows zero interest in territorial claims or resources, suggesting his attacks stem from pure malevolence or an incomprehensible alien agenda.',
    abilities: ['Flight', 'Gravity Beams', 'Hurricane Winds', 'Regeneration', 'Space Survival', 'Alpha Call'],
    attacks: ['Triple Gravity Beam', 'Wing Lightning', 'Constricting Necks', 'Meteor Strike'],
    weaknesses: ['Oxygen Destroyer (temporary)', 'Coordinated Attack on Central Head', 'Atomic Absorption Overload'],
    fanPowerIndex: 93,
    durabilityScore: 92,
    attackPowerScore: 96,
    mobilityScore: 85,
    intelligenceScore: 75,
    specialAbilitiesScore: 94,
    eraScalingFactor: 1.15,
    primaryImageUrl: 'https://placehold.co/800x600/1a1a25/00d4aa?text=King+Ghidorah',
    galleryImages: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'monster-mechagodzilla',
    name: 'Mechagodzilla',
    slug: 'mechagodzilla',
    aliases: ['MechaG', 'Kiryu', 'Super Mechagodzilla'],
    eraTags: ['Showa', 'Heisei', 'Millennium', 'MonsterVerse'],
    alignment: 'antagonist',
    speciesType: 'mech',
    firstAppearanceDate: new Date('1974-03-21'),
    firstAppearanceWorkId: 'work-godzilla-vs-mechagodzilla',
    heightMeters: 120,
    weightTons: 150000,
    originSummary: 'A mechanical replica of Godzilla created to defeat the King of the Monsters. Various iterations exist across timelines, built by alien invaders, human governments, or created from the bones of the original 1954 Godzilla. Each version represents the pinnacle of its creators\' technology.',
    lastKnownWhereabouts: 'The Apex Cybernetics facility in Hong Kong was destroyed during the Mechagodzilla rampage. Salvage operations recovered partial remains.',
    descriptionLong: 'Mechagodzilla serves as the technological answer to the kaiju problem. The Showa version was created by the Black Hole Planet 3 aliens as an invasion weapon. The Heisei Super Mechagodzilla combined UN resources into a single anti-Godzilla platform. The Millennium Kiryu took the controversial approach of building around the original Godzilla skeleton. Most recently, the Apex version used Ghidorah neural tissue as a control system, with catastrophic results.',
    abilities: ['Missile Arrays', 'Eye Lasers', 'Finger Missiles', 'Jet Flight', 'Force Field', 'Absolute Zero Cannon'],
    attacks: ['Full Weapon Barrage', 'Chest Beam', 'Drill Hand', 'Proton Scream'],
    weaknesses: ['EMP', 'Electrical Surge', 'Extended Combat Drains Power', 'Pilot Dependency'],
    fanPowerIndex: 88,
    durabilityScore: 85,
    attackPowerScore: 92,
    mobilityScore: 70,
    intelligenceScore: 65,
    specialAbilitiesScore: 90,
    eraScalingFactor: 1.1,
    primaryImageUrl: 'https://placehold.co/800x600/1a1a25/00d4aa?text=Mechagodzilla',
    galleryImages: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'monster-rodan',
    name: 'Rodan',
    slug: 'rodan',
    aliases: ['Radon', 'Fire Rodan', 'The Fire Demon'],
    eraTags: ['Showa', 'Heisei', 'MonsterVerse'],
    alignment: 'evolves',
    speciesType: 'kaiju',
    firstAppearanceDate: new Date('1956-12-26'),
    firstAppearanceWorkId: 'work-rodan-1956',
    heightMeters: 46.9,
    weightTons: 39043,
    originSummary: 'A giant pteranodon awakened from volcanic slumber. Rodan represents an ancient species that survived extinction by hibernating in geothermal vents. His body temperature runs hundreds of degrees above normal due to volcanic adaptation, and his flight speed generates devastating shockwaves.',
    lastKnownWhereabouts: 'Established nesting territory in the volcanic region of Fiji. Monarch maintains observation posts at safe distance.',
    descriptionLong: 'Rodan predates Godzilla in the fossil record, representing an evolutionary branch that achieved gigantism millions of years before the atomic age. His aerial capabilities make him uniquely dangerous. A single flyby at low altitude can level buildings through sonic shock alone. The Fire Rodan variant gained additional abilities after exposure to radiation, including a uranium heat beam. Despite his fearsome reputation, Rodan has occasionally allied with Godzilla against greater threats.',
    abilities: ['Supersonic Flight', 'Volcanic Physiology', 'Uranium Heat Beam', 'Shockwave Generation', 'Heat Resistance'],
    attacks: ['Sonic Boom Dive', 'Beak Strike', 'Wing Slash', 'Heat Beam'],
    weaknesses: ['Cold Environments', 'Ground Combat Disadvantage', 'Vulnerable to Ranged Energy Attacks'],
    fanPowerIndex: 72,
    durabilityScore: 68,
    attackPowerScore: 75,
    mobilityScore: 98,
    intelligenceScore: 55,
    specialAbilitiesScore: 70,
    eraScalingFactor: 1.0,
    primaryImageUrl: 'https://placehold.co/800x600/1a1a25/00d4aa?text=Rodan',
    galleryImages: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'monster-kong',
    name: 'Kong',
    slug: 'kong',
    aliases: ['King Kong', 'The Eighth Wonder', 'Protector of Skull Island'],
    eraTags: ['MonsterVerse', 'Other'],
    alignment: 'protagonist',
    speciesType: 'titan',
    firstAppearanceDate: new Date('1933-03-02'),
    firstAppearanceWorkId: 'work-king-kong-1933',
    heightMeters: 102.8,
    weightTons: 158000,
    originSummary: 'The last surviving member of a species of giant apes that ruled Skull Island. Kong represents the evolutionary apex of his kind, having grown significantly after relocating to Hollow Earth. Unlike most titans, Kong demonstrates tool use and tactical thinking comparable to human intelligence.',
    lastKnownWhereabouts: 'Established territory in Hollow Earth near ancestral Kong temple. Maintains surface patrols through Monarch-monitored access points.',
    descriptionLong: 'Kong occupies a unique ecological niche as a thinking titan. His species developed alongside early humans, explaining his protective instincts toward people. Archaeological evidence in Hollow Earth suggests Kongs once fought alongside ancient human civilizations against Godzilla\' species. The current Kong inherited the role of Alpha in Hollow Earth after Godzilla returned to the surface. His combat style emphasizes agility and tool use over raw power, making him a formidable opponent despite lower energy output than atomic-powered titans.',
    abilities: ['Extreme Intelligence', 'Tool Use', 'Climbing', 'Agility', 'Tactical Combat', 'Hollow Earth Adaptation'],
    attacks: ['Axe Strike', 'Grappling', 'Thrown Objects', 'Ground Pound'],
    weaknesses: ['No Ranged Attacks', 'Vulnerable to Energy Weapons', 'Emotional Attachment Exploitable'],
    fanPowerIndex: 85,
    durabilityScore: 78,
    attackPowerScore: 82,
    mobilityScore: 88,
    intelligenceScore: 95,
    specialAbilitiesScore: 72,
    eraScalingFactor: 1.1,
    primaryImageUrl: 'https://placehold.co/800x600/1a1a25/00d4aa?text=Kong',
    galleryImages: [],
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// WORKS (Movies, Series, etc.)
// ============================================================================

export const sampleWorks: Work[] = [
  {
    id: 'work-godzilla-1954',
    title: 'Godzilla (1954)',
    slug: 'godzilla-1954',
    workType: 'movie',
    releaseDate: new Date('1954-11-03'),
    eraTags: ['Showa'],
    continuityTag: 'Showa',
    synopsisLong: 'When a series of mysterious ship disappearances plague Japanese waters, an investigation leads to the discovery of Godzilla, a prehistoric creature mutated and awakened by nuclear testing. As the monster makes landfall in Tokyo, scientist Dr. Serizawa faces an impossible choice: use his devastating Oxygen Destroyer invention to stop Godzilla, knowing the weapon could threaten all of humanity if its secrets spread. The film serves as both a monster thriller and a meditation on nuclear weapons, created by filmmakers who lived through Hiroshima and Nagasaki.',
    studio: 'Toho',
    director: 'Ishiro Honda',
    runtimeMinutes: 96,
    posterImageUrl: 'https://placehold.co/300x450/1a1a25/00d4aa?text=Godzilla+1954',
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'work-mothra-1961',
    title: 'Mothra (1961)',
    slug: 'mothra-1961',
    workType: 'movie',
    releaseDate: new Date('1961-07-30'),
    eraTags: ['Showa'],
    continuityTag: 'Showa',
    synopsisLong: 'An expedition to the irradiated Infant Island discovers not only that life survives there, but that the island harbors a secret: tiny twin priestesses called the Shobijin who serve the giant moth deity Mothra. When an unscrupulous businessman kidnaps the Shobijin to exhibit them in Tokyo, Mothra hatches from her egg and begins a destructive journey across the Pacific to rescue her guardians. The film introduced one of the most beloved kaiju and established themes of environmentalism and the exploitation of indigenous peoples.',
    studio: 'Toho',
    director: 'Ishiro Honda',
    runtimeMinutes: 101,
    posterImageUrl: 'https://placehold.co/300x450/1a1a25/00d4aa?text=Mothra+1961',
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'work-ghidorah-three-headed-monster',
    title: 'Ghidorah, the Three-Headed Monster (1964)',
    slug: 'ghidorah-three-headed-monster-1964',
    workType: 'movie',
    releaseDate: new Date('1964-12-20'),
    eraTags: ['Showa'],
    continuityTag: 'Showa',
    synopsisLong: 'A princess claims to be from Venus and warns of Earth\' impending doom as a meteor shower brings King Ghidorah, the destroyer of her home world. Meanwhile, Godzilla and Rodan resume their territorial battle. When Ghidorah proves too powerful for any single creature, Mothra attempts to convince the feuding kaiju to join forces. This pivotal film marks Godzilla\' transition from villain to defender and establishes the team-up formula that would define the Showa era.',
    studio: 'Toho',
    director: 'Ishiro Honda',
    runtimeMinutes: 93,
    posterImageUrl: 'https://placehold.co/300x450/1a1a25/00d4aa?text=Ghidorah+1964',
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'work-godzilla-vs-mechagodzilla',
    title: 'Godzilla vs. Mechagodzilla (1974)',
    slug: 'godzilla-vs-mechagodzilla-1974',
    workType: 'movie',
    releaseDate: new Date('1974-03-21'),
    eraTags: ['Showa'],
    continuityTag: 'Showa',
    synopsisLong: 'Aliens from the Black Hole Planet 3 construct Mechagodzilla, a robot duplicate of the King of Monsters, to conquer Earth. When a fake Godzilla attacks Japan with unprecedented aggression, suspicions arise. The real Godzilla must face his mechanical doppelganger, aided by the ancient guardian King Caesar. The film introduced one of Godzilla\' most enduring adversaries and showcased impressive special effects for its era.',
    studio: 'Toho',
    director: 'Jun Fukuda',
    runtimeMinutes: 84,
    posterImageUrl: 'https://placehold.co/300x450/1a1a25/00d4aa?text=MechaG+1974',
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'work-godzilla-2014',
    title: 'Godzilla (2014)',
    slug: 'godzilla-2014',
    workType: 'movie',
    releaseDate: new Date('2014-05-16'),
    eraTags: ['MonsterVerse'],
    continuityTag: 'MonsterVerse',
    synopsisLong: 'Fifteen years after a nuclear plant disaster in Japan that killed his wife, Joe Brody discovers the incident was actually caused by a massive creature. When two parasitic MUTOs (Massive Unidentified Terrestrial Organisms) emerge and threaten to breed, the ancient alpha predator Godzilla surfaces to restore natural balance. The film launched the MonsterVerse franchise with a grounded approach that emphasized the awe and terror of witnessing titans clash.',
    studio: 'Legendary Pictures',
    director: 'Gareth Edwards',
    runtimeMinutes: 123,
    posterImageUrl: 'https://placehold.co/300x450/1a1a25/00d4aa?text=Godzilla+2014',
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'work-godzilla-vs-kong',
    title: 'Godzilla vs. Kong (2021)',
    slug: 'godzilla-vs-kong-2021',
    workType: 'movie',
    releaseDate: new Date('2021-03-31'),
    eraTags: ['MonsterVerse'],
    continuityTag: 'MonsterVerse',
    synopsisLong: 'When Godzilla begins attacking seemingly without provocation, Monarch launches a desperate mission to escort Kong through Hollow Earth to find a power source that might level the playing field. Unknown to most, the Apex corporation has constructed Mechagodzilla using salvaged King Ghidorah neural tissue, intending to create a titan-killer under human control. The two alpha titans collide in Hong Kong before facing a common enemy. The film delivers the long-awaited showdown while deepening MonsterVerse mythology.',
    studio: 'Legendary Pictures',
    director: 'Adam Wingard',
    runtimeMinutes: 113,
    posterImageUrl: 'https://placehold.co/300x450/1a1a25/00d4aa?text=GvK+2021',
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// APPEARANCES
// ============================================================================

export const sampleAppearances: Appearance[] = [
  // Godzilla 1954
  { id: 'app-1', monsterId: 'monster-godzilla', workId: 'work-godzilla-1954', roleTag: 'protagonist', notesShort: 'First appearance. Portrayed as a destructive force and nuclear allegory.', createdAt: new Date() },
  // Mothra 1961
  { id: 'app-2', monsterId: 'monster-mothra', workId: 'work-mothra-1961', roleTag: 'protagonist', notesShort: 'First appearance. Rescues the Shobijin from captivity.', createdAt: new Date() },
  // Ghidorah 1964
  { id: 'app-3', monsterId: 'monster-king-ghidorah', workId: 'work-ghidorah-three-headed-monster', roleTag: 'antagonist', notesShort: 'First appearance. Arrives via meteor to destroy Earth.', createdAt: new Date() },
  { id: 'app-4', monsterId: 'monster-godzilla', workId: 'work-ghidorah-three-headed-monster', roleTag: 'protagonist', notesShort: 'First heroic role. Teams up with Rodan and Mothra.', createdAt: new Date() },
  { id: 'app-5', monsterId: 'monster-mothra', workId: 'work-ghidorah-three-headed-monster', roleTag: 'protagonist', notesShort: 'Convinces Godzilla and Rodan to fight Ghidorah.', createdAt: new Date() },
  { id: 'app-6', monsterId: 'monster-rodan', workId: 'work-ghidorah-three-headed-monster', roleTag: 'protagonist', notesShort: 'Initially fights Godzilla, then joins alliance.', createdAt: new Date() },
  // Godzilla vs Mechagodzilla 1974
  { id: 'app-7', monsterId: 'monster-godzilla', workId: 'work-godzilla-vs-mechagodzilla', roleTag: 'protagonist', notesShort: 'Faces his mechanical duplicate.', createdAt: new Date() },
  { id: 'app-8', monsterId: 'monster-mechagodzilla', workId: 'work-godzilla-vs-mechagodzilla', roleTag: 'antagonist', notesShort: 'First appearance. Alien-controlled robot.', createdAt: new Date() },
  // Godzilla 2014
  { id: 'app-9', monsterId: 'monster-godzilla', workId: 'work-godzilla-2014', roleTag: 'protagonist', notesShort: 'MonsterVerse debut. Battles the MUTOs.', createdAt: new Date() },
  // Godzilla vs Kong
  { id: 'app-10', monsterId: 'monster-godzilla', workId: 'work-godzilla-vs-kong', roleTag: 'protagonist', notesShort: 'Faces Kong and later Mechagodzilla.', createdAt: new Date() },
  { id: 'app-11', monsterId: 'monster-kong', workId: 'work-godzilla-vs-kong', roleTag: 'protagonist', notesShort: 'Travels to Hollow Earth. Teams with Godzilla against Mechagodzilla.', createdAt: new Date() },
  { id: 'app-12', monsterId: 'monster-mechagodzilla', workId: 'work-godzilla-vs-kong', roleTag: 'antagonist', notesShort: 'Apex Cybernetics creation using Ghidorah neural tissue.', createdAt: new Date() },
];

// ============================================================================
// BATTLES
// ============================================================================

export const sampleBattles: Battle[] = [
  {
    id: 'battle-1',
    title: 'Tokyo Bay Emergence',
    slug: 'tokyo-bay-emergence-1954',
    workId: 'work-godzilla-1954',
    location: 'Tokyo Bay, Japan',
    summary: 'Godzilla makes his first devastating landfall in Tokyo. Despite military resistance, the creature proves unstoppable until Dr. Serizawa deploys the Oxygen Destroyer, sacrificing himself to ensure the weapon\' secret dies with him.',
    battleDate: new Date('1954-11-03'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'battle-2',
    title: 'The First Alliance',
    slug: 'first-alliance-ghidorah-1964',
    workId: 'work-ghidorah-three-headed-monster',
    location: 'Mount Fuji, Japan',
    summary: 'Godzilla, Rodan, and Mothra join forces for the first time against King Ghidorah. After Mothra\' pleas, the two feuding kaiju set aside their differences. Their combined assault drives Ghidorah from Earth.',
    battleDate: new Date('1964-12-20'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'battle-3',
    title: 'Mechagodzilla Showdown',
    slug: 'mechagodzilla-showdown-1974',
    workId: 'work-godzilla-vs-mechagodzilla',
    location: 'Okinawa, Japan',
    summary: 'Godzilla faces his mechanical double in a brutal confrontation. Initially overpowered by Mechagodzilla\' arsenal, Godzilla gains the upper hand when he discovers he can magnetize his body, drawing the robot close enough to tear it apart.',
    battleDate: new Date('1974-03-21'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'battle-4',
    title: 'Hong Kong Collision',
    slug: 'hong-kong-collision-2021',
    workId: 'work-godzilla-vs-kong',
    location: 'Hong Kong, China',
    summary: 'The long-anticipated clash between Godzilla and Kong unfolds across Hong Kong\' neon-lit streets. Godzilla proves dominant in their initial exchange, but Kong\' intelligence and newly acquired Hollow Earth axe even the odds. Their battle is interrupted by Mechagodzilla\' activation, forcing a temporary alliance.',
    battleDate: new Date('2021-03-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// BATTLE PARTICIPANTS
// ============================================================================

export const sampleBattleParticipants: BattleParticipant[] = [
  // Tokyo Bay
  { id: 'bp-1', battleId: 'battle-1', monsterId: 'monster-godzilla', outcome: 'loss', notesShort: 'Killed by Oxygen Destroyer' },
  // First Alliance
  { id: 'bp-2', battleId: 'battle-2', monsterId: 'monster-godzilla', outcome: 'win', notesShort: 'Team effort' },
  { id: 'bp-3', battleId: 'battle-2', monsterId: 'monster-rodan', outcome: 'win', notesShort: 'Team effort' },
  { id: 'bp-4', battleId: 'battle-2', monsterId: 'monster-mothra', outcome: 'win', notesShort: 'Organized the alliance' },
  { id: 'bp-5', battleId: 'battle-2', monsterId: 'monster-king-ghidorah', outcome: 'loss', notesShort: 'Retreated to space' },
  // Mechagodzilla 1974
  { id: 'bp-6', battleId: 'battle-3', monsterId: 'monster-godzilla', outcome: 'win', notesShort: 'Used magnetic powers' },
  { id: 'bp-7', battleId: 'battle-3', monsterId: 'monster-mechagodzilla', outcome: 'loss', notesShort: 'Destroyed' },
  // Hong Kong
  { id: 'bp-8', battleId: 'battle-4', monsterId: 'monster-godzilla', outcome: 'win', notesShort: 'Defeated Kong, then teamed up' },
  { id: 'bp-9', battleId: 'battle-4', monsterId: 'monster-kong', outcome: 'loss', notesShort: 'Lost to Godzilla, but survived' },
  { id: 'bp-10', battleId: 'battle-4', monsterId: 'monster-mechagodzilla', outcome: 'loss', notesShort: 'Destroyed by team effort' },
];

// ============================================================================
// RELATIONSHIPS
// ============================================================================

export const sampleRelationships: Relationship[] = [
  { id: 'rel-1', fromMonsterId: 'monster-godzilla', toMonsterId: 'monster-king-ghidorah', relationType: 'enemy', notesShort: 'Ancient rivals. Ghidorah challenges Godzilla\'s alpha status.', createdAt: new Date() },
  { id: 'rel-2', fromMonsterId: 'monster-godzilla', toMonsterId: 'monster-mothra', relationType: 'ally', notesShort: 'Symbiotic relationship spanning eras. Mothra often aids Godzilla.', createdAt: new Date() },
  { id: 'rel-3', fromMonsterId: 'monster-godzilla', toMonsterId: 'monster-rodan', relationType: 'ally', notesShort: 'Former rivals turned allies against greater threats.', createdAt: new Date() },
  { id: 'rel-4', fromMonsterId: 'monster-godzilla', toMonsterId: 'monster-mechagodzilla', relationType: 'enemy', notesShort: 'Mechanical duplicate created to destroy the original.', createdAt: new Date() },
  { id: 'rel-5', fromMonsterId: 'monster-godzilla', toMonsterId: 'monster-kong', relationType: 'rival', notesShort: 'Alpha titans with competing territorial claims.', createdAt: new Date() },
  { id: 'rel-6', fromMonsterId: 'monster-mothra', toMonsterId: 'monster-king-ghidorah', relationType: 'enemy', notesShort: 'Defender of Earth vs. its destroyer.', createdAt: new Date() },
  { id: 'rel-7', fromMonsterId: 'monster-kong', toMonsterId: 'monster-mechagodzilla', relationType: 'enemy', notesShort: 'Allied with Godzilla to destroy Mechagodzilla.', createdAt: new Date() },
];

// ============================================================================
// PRODUCTS
// ============================================================================

export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    asin: 'B08XYZ1234',
    title: 'S.H.MonsterArts Godzilla (2019) Figure',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=Godzilla+Figure',
    price: '$89.99',
    primeEligible: true,
    category: 'figures',
    brand: 'Bandai',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B08XYZ1234?tag=gojipedia-20',
    searchKeywords: ['godzilla', 'figure', 'monsterarts', 'bandai', 'kotm'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    asin: 'B07ABC5678',
    title: 'Godzilla: King of the Monsters 4K UHD Blu-ray',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=KOTM+4K',
    price: '$24.99',
    primeEligible: true,
    category: 'bluray',
    brand: 'Warner Bros',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B07ABC5678?tag=gojipedia-20',
    searchKeywords: ['godzilla', 'movie', 'bluray', '4k', 'king of monsters'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-3',
    asin: 'B09DEF9012',
    title: 'King Ghidorah Premium Scale Statue',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=Ghidorah+Statue',
    price: '$349.99',
    primeEligible: false,
    category: 'figures',
    brand: 'Prime 1 Studio',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B09DEF9012?tag=gojipedia-20',
    searchKeywords: ['ghidorah', 'statue', 'figure', 'premium', 'collectible'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    asin: 'B06GHI3456',
    title: 'Mothra Classic Poster Print 24x36',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=Mothra+Poster',
    price: '$14.99',
    primeEligible: true,
    category: 'posters',
    brand: 'Trends International',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B06GHI3456?tag=gojipedia-20',
    searchKeywords: ['mothra', 'poster', 'print', 'classic', 'wall art'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-5',
    asin: 'B08JKL7890',
    title: 'Godzilla vs. Kong T-Shirt',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=GvK+Shirt',
    price: '$19.99',
    primeEligible: true,
    category: 'shirts',
    brand: 'Legendary',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B08JKL7890?tag=gojipedia-20',
    searchKeywords: ['godzilla', 'kong', 'tshirt', 'shirt', 'apparel'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-6',
    asin: 'B07MNO1234',
    title: 'Mechagodzilla Model Kit 1/144 Scale',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=MechaG+Model',
    price: '$45.00',
    primeEligible: true,
    category: 'model_kits',
    brand: 'Bandai Spirits',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B07MNO1234?tag=gojipedia-20',
    searchKeywords: ['mechagodzilla', 'model kit', 'bandai', 'plastic model'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-7',
    asin: 'B09PQR5678',
    title: 'The Art of Godzilla: King of the Monsters',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=KOTM+Artbook',
    price: '$35.00',
    primeEligible: true,
    category: 'books',
    brand: 'Titan Books',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B09PQR5678?tag=gojipedia-20',
    searchKeywords: ['godzilla', 'art book', 'making of', 'concept art'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-8',
    asin: 'B08STU9012',
    title: 'Kong Skull Island Mondo Art Print',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=Kong+Art',
    price: '$55.00',
    primeEligible: false,
    category: 'art',
    brand: 'Mondo',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B08STU9012?tag=gojipedia-20',
    searchKeywords: ['kong', 'skull island', 'art print', 'mondo', 'collectible'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-9',
    asin: 'B05VWX3456',
    title: 'Rodan 1956 Criterion Blu-ray',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=Rodan+Bluray',
    price: '$29.99',
    primeEligible: true,
    category: 'bluray',
    brand: 'Criterion Collection',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B05VWX3456?tag=gojipedia-20',
    searchKeywords: ['rodan', 'criterion', 'bluray', 'classic', '1956'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-10',
    asin: 'B09YZA7890',
    title: 'Godzilla Complete Box Set Showa Era',
    imageUrl: 'https://placehold.co/400x400/1a1a25/00d4aa?text=Showa+Boxset',
    price: '$199.99',
    primeEligible: true,
    category: 'bluray',
    brand: 'Criterion Collection',
    amazonUrlWithTag: 'https://www.amazon.com/dp/B09YZA7890?tag=gojipedia-20',
    searchKeywords: ['godzilla', 'showa', 'box set', 'complete', 'criterion'],
    isActive: true,
    isSuggested: false,
    lastFetchedAt: new Date(),
    fetchFailCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// PRODUCT COLLECTIONS
// ============================================================================

export const sampleCollections: ProductCollection[] = [
  {
    id: 'coll-1',
    title: 'Essential Godzilla Collection',
    slug: 'essential-godzilla-collection',
    description: 'The must-have items for any Godzilla fan, from classic films to premium collectibles.',
    scopeType: 'monster',
    monsterId: 'monster-godzilla',
    workId: null,
    scopeValue: null,
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'coll-2',
    title: 'MonsterVerse Movie Collection',
    slug: 'monsterverse-movie-collection',
    description: 'All the MonsterVerse films in stunning 4K quality.',
    scopeType: 'era',
    monsterId: null,
    workId: null,
    scopeValue: 'MonsterVerse',
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// COLLECTION ITEMS
// ============================================================================

export const sampleCollectionItems: ProductCollectionItem[] = [
  { id: 'ci-1', collectionId: 'coll-1', productId: 'prod-1', rank: 1, reasonLine: 'The definitive modern Godzilla figure with incredible detail.', createdAt: new Date() },
  { id: 'ci-2', collectionId: 'coll-1', productId: 'prod-2', rank: 2, reasonLine: 'Experience the MonsterVerse in stunning 4K.', createdAt: new Date() },
  { id: 'ci-3', collectionId: 'coll-1', productId: 'prod-7', rank: 3, reasonLine: 'Gorgeous concept art and behind-the-scenes insights.', createdAt: new Date() },
  { id: 'ci-4', collectionId: 'coll-1', productId: 'prod-10', rank: 4, reasonLine: 'The complete classic era in one beautiful set.', createdAt: new Date() },
  { id: 'ci-5', collectionId: 'coll-2', productId: 'prod-2', rank: 1, reasonLine: 'The film that reignited the franchise.', createdAt: new Date() },
  { id: 'ci-6', collectionId: 'coll-2', productId: 'prod-5', rank: 2, reasonLine: 'Show your MonsterVerse allegiance.', createdAt: new Date() },
];

// ============================================================================
// POSTS
// ============================================================================

export const samplePosts: Post[] = [
  {
    id: 'post-1',
    title: 'A Complete History of Godzilla Across Eras',
    slug: 'complete-history-godzilla-eras',
    postType: 'article',
    status: 'published',
    storyPerspective: null,
    excerpt: 'From atomic metaphor to planetary defender, Godzilla has undergone more transformations than any other movie monster. This guide traces his evolution across seven decades of cinema.',
    mdxPath: '/content/articles/complete-history-godzilla.mdx',
    tags: ['godzilla', 'history', 'eras', 'guide'],
    categories: ['Guides', 'History'],
    metaTitle: 'Complete Godzilla History Guide | Gojipedia',
    metaDescription: 'Explore Godzilla\'s complete history from 1954 to present across the Showa, Heisei, Millennium, Reiwa, and MonsterVerse eras.',
    featuredImageUrl: 'https://placehold.co/800x400/1a1a25/00d4aa?text=Godzilla+Eras',
    publishedAt: new Date('2024-01-15'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-2',
    title: 'Understanding the Fan Power Index',
    slug: 'understanding-fan-power-index',
    postType: 'explainer',
    status: 'published',
    storyPerspective: null,
    excerpt: 'Our Fan Power Index ranks kaiju based on measurable attributes and combat history. Here\'s exactly how we calculate these scores and what they mean.',
    mdxPath: '/content/articles/fan-power-index-explained.mdx',
    tags: ['fan power index', 'rankings', 'methodology'],
    categories: ['Explainers'],
    metaTitle: 'Fan Power Index Explained | Gojipedia',
    metaDescription: 'Learn how Gojipedia calculates the Fan Power Index for every monster in our database.',
    featuredImageUrl: 'https://placehold.co/800x400/1a1a25/00d4aa?text=FPI+Explained',
    publishedAt: new Date('2024-02-01'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-3',
    title: 'The Last Lighthouse Keeper',
    slug: 'the-last-lighthouse-keeper',
    postType: 'story',
    status: 'published',
    storyPerspective: 'human',
    excerpt: 'Matsuo had manned the lighthouse on Odo Island for forty years. He thought he had seen everything the sea could offer. He was wrong.',
    mdxPath: '/content/stories/last-lighthouse-keeper.mdx',
    tags: ['short story', 'odo island', 'human perspective'],
    categories: ['Short Stories'],
    metaTitle: 'The Last Lighthouse Keeper | Gojipedia Stories',
    metaDescription: 'A short story about a lighthouse keeper\'s encounter with something ancient rising from the depths.',
    featuredImageUrl: 'https://placehold.co/800x400/1a1a25/00d4aa?text=Lighthouse+Story',
    publishedAt: new Date('2024-03-10'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
